services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./dev_resources/init.sql:/docker-entrypoint-initdb.d/init.sql