services:
  streamlit:
    build:
      context: .
      dockerfile: ./demo/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - HF_API_KEY=${HF_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}