site_name: OpenPO Documentation
site_url: https://docs.openpo.dev
site_author: Daniel Lee
repo_url: https://github.com/dannylee1020/openpo
repo_name: dannylee1020/openpo
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-colors-scheme:dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    - content.code.copy
    - def_list
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [openpo]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symobl_type_toc: true
            heading_level: 3
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            docstring_section_style: table

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - attr_list
  - md_in_html


nav:
  - Welcome: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Usage: usage.md
  - Structured Output (JSON Mode): json.md
  - Storage: storage.md
  - Providers: provider.md
  - Parameters: parameters.md
  - Responses: response.md
  - Errors: errors.md
  - Resources: resource.md
  - API Reference: api.md
