site_name: OpenPO Documentation
site_url: https://docs.openpo.dev
site_author: Daniel Lee
repo_url: https://github.com/dannylee1020/openpo
repo_name: dannylee1020/openpo
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-colors-scheme:dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    - content.code.copy
    - def_list
  icon:
    repo: fontawesome/brands/github

# Extension for better code blocks, admonitions, etc.
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets

nav:
  - Welcome: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Usage: usage.md
  - Structured Output (JSON Mode): json.md
  - Storage: storage.md
  - Parameters: parameters.md
  - Responses: response.md
  - Errors: errors.md
  - API Reference: api.md
